name: summer_school_microbiome
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastp
  - metaphlan
  - krona
  - pandas
  - plotnine
  - scikit-bio
  - scikit-learn
  - seaborn
  - plotly
  - ipykernel
  - taxopy
  - nbformat>4.2.0
