name: summer_school_microbiome
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - adapterremoval=2.3.2
  - anyio=3.3.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcbio-gff=0.6.6
  - biom-format=2.1.10
  - biopython=1.79
  - blast=2.12.0
  - bleach=4.0.0
  - boost-cpp=1.74.0
  - bowtie2=2.4.4
  - brotlipy=0.7.0
  - bx-python=0.8.11
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.7.5
  - cachecontrol=0.12.6
  - cached-property=1.5.2
  - cached_property=1.5.2
  - capnproto=0.6.1
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.1
  - cmseq=1.0.2
  - cryptography=3.4.7
  - curl=7.78.0
  - cycler=0.10.0
  - cython=0.29.24
  - debugpy=1.4.1
  - decorator=5.0.9
  - defusedxml=0.7.1
  - dendropy=4.5.2
  - descartes=1.1.0
  - diamond=2.0.11
  - entrez-direct=13.9
  - entrypoints=0.3
  - expat=2.4.1
  - fasttree=2.1.10
  - freetype=2.10.4
  - future=0.18.2
  - giflib=5.2.1
  - gsl=2.6
  - h5py=3.3.0
  - hdf5=1.10.6
  - hdmedians=0.14.2
  - htslib=1.13
  - icu=68.1
  - idna=3.2
  - importlib-metadata=4.6.3
  - iniconfig=1.1.1
  - ipykernel=6.0.3
  - ipyparallel=6.3.0
  - ipython=7.26.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - iqtree=2.1.4_beta
  - jedi=0.18.0
  - jinja2=3.0.1
  - joblib=1.0.1
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.10.2
  - jupyterlab=3.1.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.6.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - krona=2.8
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.78.0
  - libdeflate=1.7
  - libedit=3.1.20210216
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.1.0
  - libgfortran-ng=11.1.0
  - libgfortran5=11.1.0
  - libgomp=11.1.0
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=11.1.0
  - libtiff=4.2.0
  - libuv=1.42.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lockfile=0.12.2
  - lz4-c=1.9.3
  - lzo=2.10
  - mafft=7.487
  - markupsafe=2.0.1
  - mash=2.3
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - metaphlan=3.0.13
  - mistune=0.8.4
  - mizani=0.7.3
  - more-itertools=8.8.0
  - msgpack-python=1.0.2
  - muscle=3.8.1551
  - natsort=7.1.1
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - nbclassic=0.3.1
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - nodejs=16.6.1
  - notebook=6.4.2
  - numpy=1.21.1
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=21.0
  - palettable=3.3.0
  - pandas=1.3.1
  - pandoc=2.14.1
  - pandocfilters=1.4.3
  - parso=0.8.2
  - patsy=0.5.1
  - pcre=8.45
  - perl=5.26.2
  - perl-app-cpanminus=1.7044
  - perl-archive-tar=2.32
  - perl-base=2.23
  - perl-business-isbn=3.004
  - perl-business-isbn-data=20140910.003
  - perl-carp=1.38
  - perl-common-sense=3.74
  - perl-compress-raw-bzip2=2.087
  - perl-compress-raw-zlib=2.087
  - perl-constant=1.33
  - perl-data-dumper=2.173
  - perl-digest-hmac=1.03
  - perl-digest-md5=2.55
  - perl-encode=2.88
  - perl-encode-locale=1.05
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002001
  - perl-extutils-makemaker=7.36
  - perl-file-listing=6.04
  - perl-file-path=2.16
  - perl-file-temp=0.2304
  - perl-html-parser=3.72
  - perl-html-tagset=3.20
  - perl-html-tree=5.07
  - perl-http-cookies=6.04
  - perl-http-daemon=6.01
  - perl-http-date=6.02
  - perl-http-message=6.18
  - perl-http-negotiate=6.01
  - perl-io-compress=2.087
  - perl-io-html=1.001
  - perl-io-socket-ssl=2.066
  - perl-io-zlib=1.10
  - perl-json=4.02
  - perl-json-xs=2.34
  - perl-libwww-perl=6.39
  - perl-list-moreutils=0.428
  - perl-list-moreutils-xs=0.428
  - perl-lwp-mediatypes=6.04
  - perl-lwp-protocol-https=6.07
  - perl-mime-base64=3.15
  - perl-mozilla-ca=20180117
  - perl-net-http=6.19
  - perl-net-ssleay=1.88
  - perl-ntlm=1.09
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.52
  - perl-socket=2.027
  - perl-storable=3.15
  - perl-test-requiresinternet=0.05
  - perl-time-local=1.28
  - perl-try-tiny=0.30
  - perl-types-serialiser=1.0
  - perl-uri=1.76
  - perl-www-robotrules=6.02
  - perl-xml-namespacesupport=1.12
  - perl-xml-parser=2.44_01
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - perl-xml-sax-expat=0.51
  - perl-xml-simple=2.25
  - perl-xsloader=0.24
  - pexpect=4.8.0
  - phylophlan=3.0.2
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.3
  - plotly=5.2.1
  - plotly_express=0.4.1
  - plotnine=0.8.0
  - pluggy=0.13.1
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.19
  - ptyprocess=0.7.0
  - py=1.10.0
  - pycparser=2.20
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.18.0
  - pysam=0.16.0.1
  - pysocks=1.7.1
  - pytest=6.2.4
  - python=3.9.6
  - python-dateutil=2.8.2
  - python-lzo=1.12
  - python_abi=3.9
  - pytz=2021.1
  - pyzmq=22.2.1
  - raxml=8.2.12
  - readline=8.1
  - requests=2.26.0
  - requests-unixsocket=0.2.0
  - samtools=1.13
  - scikit-bio=0.5.6
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - send2trash=1.8.0
  - seqkit=0.16.1
  - seqtk=1.3
  - setuptools=52.0.0
  - six=1.16.0
  - sniffio=1.2.0
  - sourcetracker=2.0.1
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - tbb=2020.3
  - tenacity=8.0.1
  - terminado=0.10.1
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - traitlets=5.0.5
  - trimal=1.4.1
  - tzdata=2021a
  - urllib3=1.26.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
